# Project: bit_wise_operations
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = main.o bit_wise_operations.o
LINKOBJ  = main.o bit_wise_operations.o
LIBS     = -L"C:/shravan/Dev-Cpp/MinGW64/lib" -L"C:/shravan/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc
INCS     = -I"C:/shravan/Dev-Cpp/MinGW64/include" -I"C:/shravan/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/shravan/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"C:/shravan/Dev-Cpp/MinGW64/include" -I"C:/shravan/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/shravan/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"C:/shravan/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = bit_wise_operations.exe
CXXFLAGS = $(CXXINCS) 
CFLAGS   = $(INCS) 
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CC) $(LINKOBJ) -o $(BIN) $(LIBS)

main.o: main.c
	$(CC) -c main.c -o main.o $(CFLAGS)

bit_wise_operations.o: bit_wise_operations.c
	$(CC) -c bit_wise_operations.c -o bit_wise_operations.o $(CFLAGS)
